version: "3.6"
services:
  db12:
    image: postgres:12
    ports:
      - 127.0.0.1:65432:5432
    restart: unless-stopped
    volumes:
      - postgres12-data:/var/lib/postgresql/data
      - ./postgres12.conf:/etc/postgresql.conf
    command: -p 5432 -c config_file=/etc/postgresql.conf
    environment:
      - TZ=Europe/Budapest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      default:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 127.0.0.1:8888:80
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin_servers.json:/pgadmin4/servers.json
    environment:
      - TZ=Europe/Budapest
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.hu
      - PGADMIN_DEFAULT_PASSWORD=postgres
networks:
  default:
volumes:
  pgadmin-data:
  postgres12-data:
